"""Coordinator Agent - Central knowledge repository and context provider for all agents."""

import logging
import json
from typing import Dict, List, Optional
from datetime import datetime
from pathlib import Path

from .base_agent import BaseAgent
from ..rag.retriever import Retriever

logger = logging.getLogger(__name__)


class CoordinatorAgent(BaseAgent):
    """Agent that coordinates between all agents, maintains knowledge base, and ensures consistency."""
    
    def __init__(self, retriever: Retriever, model: str = "gpt-4-turbo-preview"):
        """
        Initialize Coordinator Agent.
        
        Args:
            retriever: Retriever instance for RAG
            model: LLM model name
        """
        super().__init__("coordinator", retriever, model=model)
        self.knowledge_base = {}  # In-memory knowledge store
        self.knowledge_dir = Path("data/coordinator_knowledge")
        self.knowledge_dir.mkdir(parents=True, exist_ok=True)
        logger.info("CoordinatorAgent initialized")
    
    def store_generated_content(self, company_id: str, agent_name: str, 
                                content_type: str, content: Dict) -> None:
        """
        Store content generated by an agent.
        
        Args:
            company_id: Company identifier
            agent_name: Name of the agent that generated content
            content_type: Type of content (e.g., "pitch", "marketing_content", "job_description")
            content: Content to store
        """
        logger.info(f"Storing {content_type} from {agent_name} for company {company_id}")
        
        if company_id not in self.knowledge_base:
            self.knowledge_base[company_id] = {
                "company_data": {},
                "generated_content": {},
                "discussions": [],
                "decisions": {},
                "last_updated": datetime.now().isoformat()
            }
        
        if "generated_content" not in self.knowledge_base[company_id]:
            self.knowledge_base[company_id]["generated_content"] = {}
        
        if agent_name not in self.knowledge_base[company_id]["generated_content"]:
            self.knowledge_base[company_id]["generated_content"][agent_name] = {}
        
        self.knowledge_base[company_id]["generated_content"][agent_name][content_type] = {
            "content": content,
            "timestamp": datetime.now().isoformat(),
            "agent": agent_name
        }
        
        # Persist to file
        self._save_knowledge_base(company_id)
    
    def store_company_data(self, company_id: str, company_data: Dict) -> None:
        """
        Store company data.
        
        Args:
            company_id: Company identifier
            company_data: Company information
        """
        logger.info(f"Storing company data for {company_id}")
        
        if company_id not in self.knowledge_base:
            self.knowledge_base[company_id] = {
                "company_data": {},
                "generated_content": {},
                "discussions": [],
                "decisions": {},
                "last_updated": datetime.now().isoformat()
            }
        
        self.knowledge_base[company_id]["company_data"] = company_data
        self.knowledge_base[company_id]["last_updated"] = datetime.now().isoformat()
        
        # Persist to file
        self._save_knowledge_base(company_id)
    
    def get_context_for_agent(self, company_id: str, agent_name: str, 
                              query: Optional[str] = None) -> Dict:
        """
        Get relevant context for an agent based on what other agents have generated.
        
        Args:
            company_id: Company identifier
            agent_name: Name of the agent requesting context
            query: Optional query to filter relevant context
            
        Returns:
            Dictionary with relevant context
        """
        logger.info(f"Getting context for {agent_name} (company: {company_id})")
        
        # Load knowledge base if not in memory
        if company_id not in self.knowledge_base:
            self._load_knowledge_base(company_id)
        
        if company_id not in self.knowledge_base:
            return {
                "company_data": {},
                "relevant_content": [],
                "summary": "No previous context found for this company."
            }
        
        knowledge = self.knowledge_base[company_id]
        company_data = knowledge.get("company_data", {})
        generated_content = knowledge.get("generated_content", {})
        
        # Collect relevant content from other agents
        relevant_content = []
        for agent, content_dict in generated_content.items():
            if agent != agent_name:  # Don't include own content
                for content_type, content_data in content_dict.items():
                    relevant_content.append({
                        "agent": agent,
                        "type": content_type,
                        "summary": self._summarize_content(content_data.get("content", {})),
                        "timestamp": content_data.get("timestamp", "")
                    })
        
        # Generate summary
        summary = self._generate_context_summary(company_data, relevant_content, agent_name, query)
        
        return {
            "company_data": company_data,
            "relevant_content": relevant_content,
            "summary": summary,
            "discussions": knowledge.get("discussions", []),
            "decisions": knowledge.get("decisions", {})
        }
    
    def get_company_knowledge(self, company_id: str) -> Dict:
        """
        Get all knowledge about a company.
        
        Args:
            company_id: Company identifier
            
        Returns:
            Complete knowledge base for the company
        """
        if company_id not in self.knowledge_base:
            self._load_knowledge_base(company_id)
        
        return self.knowledge_base.get(company_id, {})
    
    def check_consistency(self, company_id: str, new_content: Dict, 
                         content_type: str) -> Dict:
        """
        Check if new content is consistent with previously generated content.
        
        Args:
            company_id: Company identifier
            new_content: New content to check
            content_type: Type of content
            
        Returns:
            Consistency check results
        """
        logger.info(f"Checking consistency for {content_type} (company: {company_id})")
        
        if company_id not in self.knowledge_base:
            self._load_knowledge_base(company_id)
        
        if company_id not in self.knowledge_base:
            return {
                "consistent": True,
                "warnings": [],
                "suggestions": []
            }
        
        knowledge = self.knowledge_base[company_id]
        existing_content = knowledge.get("generated_content", {})
        company_data = knowledge.get("company_data", {})
        
        # Use LLM to check consistency
        existing_summaries = []
        for agent, content_dict in existing_content.items():
            for ct, content_data in content_dict.items():
                existing_summaries.append(
                    f"{agent} ({ct}): {self._summarize_content(content_data.get('content', {}))}"
                )
        
        prompt = f"""Check if this new {content_type} content is consistent with previously generated content:

COMPANY DATA:
{json.dumps(company_data, indent=2)}

EXISTING CONTENT:
{chr(10).join(existing_summaries) if existing_summaries else 'No existing content'}

NEW CONTENT:
{json.dumps(new_content, indent=2)}

Check for:
1. Consistency in company information (name, industry, stage, etc.)
2. Alignment with previous decisions
3. Contradictions or conflicts
4. Missing information that was mentioned before

Return JSON with:
- "consistent": true/false
- "warnings": [list of warnings]
- "suggestions": [list of suggestions for improvement]"""
        
        system_prompt = """You are a consistency checker. Analyze content for consistency and alignment 
with previous outputs. Be thorough but fair."""
        
        try:
            response_text = self.generate_response(prompt, system_prompt=system_prompt)
            # Try to parse JSON from response
            if "```json" in response_text:
                json_start = response_text.find("```json") + 7
                json_end = response_text.find("```", json_start)
                response_text = response_text[json_start:json_end].strip()
            elif "```" in response_text:
                json_start = response_text.find("```") + 3
                json_end = response_text.find("```", json_start)
                response_text = response_text[json_start:json_end].strip()
            
            result = json.loads(response_text)
            return result
        except Exception as e:
            logger.warning(f"Error checking consistency: {e}")
            return {
                "consistent": True,
                "warnings": [],
                "suggestions": []
            }
    
    def add_discussion(self, company_id: str, agent_name: str, topic: str, 
                      summary: str) -> None:
        """
        Add a discussion record.
        
        Args:
            company_id: Company identifier
            agent_name: Agent that had the discussion
            topic: Discussion topic
            summary: Summary of discussion
        """
        if company_id not in self.knowledge_base:
            self.knowledge_base[company_id] = {
                "company_data": {},
                "generated_content": {},
                "discussions": [],
                "decisions": {},
                "last_updated": datetime.now().isoformat()
            }
        
        self.knowledge_base[company_id]["discussions"].append({
            "timestamp": datetime.now().isoformat(),
            "agent": agent_name,
            "topic": topic,
            "summary": summary
        })
        
        self._save_knowledge_base(company_id)
    
    def _summarize_content(self, content: Dict) -> str:
        """Summarize content for context."""
        if isinstance(content, dict):
            if "response" in content:
                response = content["response"]
                # Get first 200 chars
                return response[:200] + "..." if len(response) > 200 else response
            return str(content)[:200]
        return str(content)[:200]
    
    def _generate_context_summary(self, company_data: Dict, relevant_content: List[Dict],
                                 agent_name: str, query: Optional[str] = None) -> str:
        """Generate a summary of context for an agent."""
        if not relevant_content and not company_data:
            return "No previous context available."
        
        summary_parts = []
        
        if company_data:
            summary_parts.append(f"Company: {company_data.get('company_name', 'Unknown')}")
            if company_data.get('industry'):
                summary_parts.append(f"Industry: {company_data.get('industry')}")
            if company_data.get('current_stage'):
                summary_parts.append(f"Stage: {company_data.get('current_stage')}")
        
        if relevant_content:
            summary_parts.append("\nPreviously generated content:")
            for item in relevant_content[:5]:  # Limit to 5 most recent
                summary_parts.append(f"- {item['agent']} generated {item['type']}")
        
        return "\n".join(summary_parts)
    
    def _save_knowledge_base(self, company_id: str) -> None:
        """Save knowledge base to file."""
        try:
            file_path = self.knowledge_dir / f"{company_id}.json"
            with open(file_path, 'w') as f:
                json.dump(self.knowledge_base.get(company_id, {}), f, indent=2)
        except Exception as e:
            logger.error(f"Error saving knowledge base: {e}")
    
    def _load_knowledge_base(self, company_id: str) -> None:
        """Load knowledge base from file."""
        try:
            file_path = self.knowledge_dir / f"{company_id}.json"
            if file_path.exists():
                with open(file_path, 'r') as f:
                    self.knowledge_base[company_id] = json.load(f)
        except Exception as e:
            logger.error(f"Error loading knowledge base: {e}")
    
    def process_query(self, query: str, context: Optional[Dict] = None) -> Dict:
        """
        Process a coordinator-related query.
        
        Args:
            query: User query
            context: Optional context
            
        Returns:
            Agent response
        """
        company_id = context.get("company_id", "default") if context else "default"
        
        # Load knowledge
        knowledge = self.get_company_knowledge(company_id)
        
        prompt = f"""User Query: {query}

Company Knowledge Base:
{json.dumps(knowledge, indent=2) if knowledge else 'No knowledge available'}

Answer the query based on the knowledge base. If information is missing, say so."""
        
        system_prompt = """You are a coordinator agent that maintains knowledge about companies and 
their generated content. Provide helpful summaries and information based on what has been stored."""
        
        response_text = self.generate_response(prompt, system_prompt=system_prompt)
        
        return self.format_response(
            response=response_text,
            sources=[]
        )

